# Generated by Django 5.1.5 on 2025-01-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.IntegerField(default=1),
        ),
    ]
