# Generated by Django 5.1.5 on 2025-01-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_author_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
